version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: documentation/public/requirements.txt

mkdocs:
  configuration: documentation/public/mkdocs.yml
