site_name: Yggdrasil Decision Forests' documentation
site_url: https://ydf.readthedocs.io/
site_description: "Yggdrasil Decision Forests (YDF) is a library to train, evaluate, interpret, and productionize decision forest models such as Random Forest and Gradient Boosted Decision Trees. YDF is available in Python, C++, CLI, JavaScript and Go."
repo_url: https://github.com/google/yggdrasil-decision-forests
repo_name: google/yggdrasil-decision-forests

theme:
  name: material
  logo: image/logo_bg.png
  favicon: image/favicon.png
  font:
    text: Roboto

  features:
    - navigation.tracking
    # - navigation.instant # TODO: Broken in development mode.
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - search.suggest

  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - style/extra.css

strict: false # TODO: Set to true before release.

nav:
  - Home: index.md
  - 'Getting Started 🧭': tutorial/getting_started.ipynb
  - Hyper-parameters 🔥: hyperparameters.md
  - API Reference 🐜: py_api/index.md
  - FAQ 🗨️: faq.md
  - Glossary 📙: glossary.md
  - For Googlers: http://go/ydf
  - Guides:
    - What are decision forests?: https://developers.google.com/machine-learning/decision-forests
    - Improve model quality: guide_how_to_improve_model.md
    - Improve training speed: guide_how_to_improve_learner.md
  - Task:
    - Classification: tutorial/classification.ipynb
    - Regression: tutorial/regression.ipynb
    - Ranking: tutorial/ranking.ipynb
    - Uplifting: tutorial/uplifting.ipynb
  - Input feature:
    - numerical: tutorial/numerical_feature.ipynb
    - categorical: tutorial/categorical_feature.ipynb
    - monotonic: tutorial/monotonic_feature.ipynb
    - pretrained embedding: tutorial/pretrained_embedding.ipynb
    - time sequences: tutorial/time_sequences.ipynb
    - multi-dimensional:  tutorial/multidimensional_feature.ipynb
    # TODO: boolean, and text
  - Dataset:
    - Pandas: tutorial/pandas.ipynb
    - tf.data.Dataset: tutorial/tf_dataset.ipynb
    # TODO: Add Dictionary, CSV, TF Dataset, TFRecord
  - Modeling:
    - Tuning: tutorial/tuning.ipynb
    - Distributed training: tutorial/distributed_training.ipynb
  - Evaluation:
    - Train & test: tutorial/train_and_test.ipynb
    - Cross-validation: tutorial/cross_validation.ipynb
  - Interpretation:
    - Counterfactual: tutorial/counterfactual.ipynb
    - Model understanding: tutorial/model_understanding.ipynb
    - Prediction understanding: tutorial/prediction_understanding.ipynb
  - Serving:
    - C++: tutorial/cpp.ipynb
    - TF Serving: tutorial/tf_serving.ipynb
    # TODO: Add Benchmarking, C++, Go, Cli, Python, F Serving, and Js
  - Advanced:
    - Inspecting trees: tutorial/inspecting_trees.ipynb
    - Editing trees: tutorial/editing_trees.ipynb
  #  - example distance: tutorial/example_distance.ipynb
    # TODO: model inspection, manual tree creation, custom loss.
  - Other APIs:
    - TensorFlow Decision Forests 🔗: https://www.tensorflow.org/decision_forests
    - CLI quickstart: cli_quickstart.md
    - CLI & C++ user manual: cli_user_manual.md
    - CLI commands: cli_commands.md
    - CLI examples: https://github.com/google/yggdrasil-decision-forests/tree/main/examples
    - C++ examples: https://github.com/google/yggdrasil-decision-forests/tree/main/examples/standalone
  - Changelog: changelog.md
  - Long-time support: lts.md
  - Contact: contact.md

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          # paths: [../../port/python]  # For dev
          import:
            - https://docs.python.org/3/objects.inv
          options:
            preload_modules:
              - ydf  # For prod
              - yggdrasil_decision_forests # For prod
            show_root_heading: true
            heading_level: 2
            inherited_members: true
            docstring_style: google
            members_order: alphabetical
            show_source: false
            show_bases: true
            show_submodules: true
            # This is currently the only way to show annotations for constructor arguments.
            merge_init_into_class: true
            show_if_no_docstring: false
            show_signature_annotations: true
            show_docstring_attributes: true
            allow_inspection: true
            show_root_full_path: false
            docstring_section_style: list
            signature_crossrefs: true
            show_signature: true
            separate_signature: true

  - macros
  - mkdocs-jupyter:
      execute: false
      include: ["*.ipynb"]
      allow_errors: false
      include_requirejs: false
  - gen-files:
      scripts:
        - copy_external.py

extra:
  analytics:
    provider: google
    property: G-R7F46HQLK0

watch:
  - ../../CONTRIBUTING.md
  - ../../LICENSE
  - ../../CHANGELOG.md

